GET http://localhost:8080/users

###
GET http://localhost:8080/users?id=12
Authorization: 3idrnaib2ia


###
PUT http://localhost:8080/users
Authorization: labt92nnngl
Content-Type: application/json

{
    "age":33,
    "email":"some@mail.com",
    "name":"some",
    "workingPosition": 3
}

###
GET http://localhost:8080/users?name=me
Authorization: ggwnffo7n6b

###
DELETE http://localhost:8080/users?id=123
Authorization: ggwnffo7n6b