GET http://localhost:8080/users

###
GET http://localhost:8080/users?id=12
Authorization: 3idrnaib2ia


###
PUT http://localhost:8080/users
Authorization: huumg1q7btm
Content-Type: application/json

{
    "age":33,
    "email":"some@mail.com",
    "name":"some",
    "workingPosition": 3
}

###
GET http://localhost:8080/users?name=me
Authorization: hollrcgvmn

###
DELETE http://localhost:8080/users?id=123
Authorization: hollrcgvmn